<?php

/**
 * AccesosconductoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccesosconductoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccesosconductoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Accesosconductores');
    }
}