<?php

/**
 * AccesousuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccesousuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccesousuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Accesousuarios');
    }
}