<?php

/**
 * AdminChoferesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminChoferesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminChoferesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminChoferes');
    }
}