<?php

/**
 * CertmedicosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CertmedicosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CertmedicosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Certmedicos');
    }
}