<?php

/**
 * ClaseservicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaseservicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaseservicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Claseservicio');
    }
}