<?php

/**
 * ConductoresxclienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConductoresxclienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConductoresxclienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conductoresxcliente');
    }
}