<?php

/**
 * CtacteturismoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CtacteturismoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CtacteturismoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ctacteturismo');
    }
}