<?php

/**
 * DepositosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepositosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepositosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Depositos');
    }
}