<?php

/**
 * DiagnosticosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiagnosticosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiagnosticosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Diagnosticos');
    }
}