<?php

/**
 * DistcubiertasinternosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistcubiertasinternosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistcubiertasinternosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Distcubiertasinternos');
    }
}