<?php

/**
 * EmpleadoresporestructuraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleadoresporestructuraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleadoresporestructuraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleadoresporestructura');
    }
}