<?php

/**
 * EstadoCubiertasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoCubiertasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoCubiertasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoCubiertas');
    }
}