<?php

/**
 * EstacionespeajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstacionespeajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstacionespeajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estacionespeaje');
    }
}