<?php

/**
 * EstadosDiagramaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosDiagramaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosDiagramaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadosDiagrama');
    }
}