<?php

/**
 * ExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Examenes');
    }
}