<?php

/**
 * FrancosdiariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrancosdiariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrancosdiariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Francosdiarios');
    }
}