<?php

/**
 * HistorialNovedadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistorialNovedadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistorialNovedadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistorialNovedades');
    }
}