<?php

/**
 * HistorialEmpleadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistorialEmpleadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistorialEmpleadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistorialEmpleados');
    }
}