<?php

/**
 * HorariosOrdenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorariosOrdenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorariosOrdenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorariosOrdenes');
    }
}