<?php

/**
 * LicenciasxcronogramaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicenciasxcronogramaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicenciasxcronogramaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Licenciasxcronograma');
    }
}