<?php

/**
 * LicenciasxconductorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicenciasxconductorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicenciasxconductorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Licenciasxconductor');
    }
}