<?php

/**
 * MapasCronogramasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapasCronogramasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapasCronogramasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapasCronogramas');
    }
}