<?php

/**
 * MedidasCubiertasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedidasCubiertasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedidasCubiertasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedidasCubiertas');
    }
}