<?php

/**
 * MensajesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensajes');
    }
}