<?php

/**
 * ModuloestructuraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuloestructuraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModuloestructuraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Moduloestructura');
    }
}