<?php

/**
 * NacionalidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NacionalidadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NacionalidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nacionalidades');
    }
}