<?php

/**
 * NormativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NormativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NormativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Normativa');
    }
}