<?php

/**
 * NovedadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovedadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovedadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Novedades');
    }
}