<?php

/**
 * OrdenesTurismoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenesTurismoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenesTurismoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenesTurismo');
    }
}