<?php

/**
 * OrdenesModificadasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenesModificadasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenesModificadasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenesModificadas');
    }
}