<?php

/**
 * OrdenesLauraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenesLauraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenesLauraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenesLaura');
    }
}