<?php

/**
 * PeajesporcronogramasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeajesporcronogramasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeajesporcronogramasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peajesporcronogramas');
    }
}