<?php

/**
 * PreciopeajeunidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreciopeajeunidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreciopeajeunidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preciopeajeunidad');
    }
}