<?php

/**
 * PropietariounidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropietariounidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropietariounidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Propietariounidad');
    }
}