<?php

/**
 * RestclientetipovtvunidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestclientetipovtvunidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestclientetipovtvunidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Restclientetipovtvunidad');
    }
}