<?php

/**
 * TiposfrancoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposfrancoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposfrancoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tiposfranco');
    }
}