<?php

/**
 * TipovencimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipovencimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipovencimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipovencimiento');
    }
}