<?php

/**
 * VacacionespersonalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VacacionespersonalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VacacionespersonalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vacacionespersonal');
    }
}