<?php

/**
 * EstructurasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstructurasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstructurasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estructuras');
    }
    
    public function getEstructura($str = null)
    {
           $q = Doctrine_Query::create()->from('Estructuras e')->where('e.id = ?', 1);
           return $q->fetchOne();
    }
}
