<?php

/**
 * UnidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Unidades');
    }
    
    public function findActivos($hydrationMode = null)
    {
           return Doctrine_Query::create()->select('u.*')->from('Unidades  u')->where('u.activo = ?', '1')->orderBy('u.interno ASC')->execute();
    }
}
