<?php

/**
 * CiudadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CiudadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CiudadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ciudades');
    }
}