<?php

/**
 * ClientesporusuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientesporusuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientesporusuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clientesporusuarios');
    }
}