<?php

/**
 * ClienterestriccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienterestriccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienterestriccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clienterestriccion');
    }
}