<?php

/**
 * CodnovpormoduloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodnovpormoduloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodnovpormoduloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Codnovpormodulo');
    }
}