<?php

/**
 * CodNovedadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodNovedadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodNovedadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodNovedades');
    }
}