<?php

/**
 * ContactosxclienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactosxclienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactosxclienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contactosxcliente');
    }
}