<?php

/**
 * ContratosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContratosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContratosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contratos');
    }
}