<?php

/**
 * CronogramasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CronogramasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CronogramasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cronogramas');
    }
}