<?php

/**
 * CtactevacacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CtactevacacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CtactevacacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ctactevacaciones');
    }
}