<?php

/**
 * CtrosasistencialesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CtrosasistencialesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CtrosasistencialesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ctrosasistenciales');
    }
}