<?php

/**
 * CubiertasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CubiertasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CubiertasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cubiertas');
    }
}