<?php

/**
 * CubiertainternoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CubiertainternoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CubiertainternoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cubiertainterno');
    }
}