<?php

/**
 * EmpleadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleados');
    }
}