<?php

/**
 * EmpleadoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleadoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleadoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleadores');
    }
}