<?php

/**
 * EspecialidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EspecialidadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EspecialidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Especialidades');
    }
}