<?php

/**
 * EstadoDiagramasDiariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoDiagramasDiariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoDiagramasDiariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoDiagramasDiarios');
    }
}