<?php

/**
 * HistorialLicenciasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistorialLicenciasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistorialLicenciasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistorialLicencias');
    }
}