<?php

/**
 * LicenciaconductorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicenciaconductorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicenciaconductorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Licenciaconductor');
    }
}