<?php

/**
 * LicenciasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LicenciasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LicenciasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Licencias');
    }
}