<?php

/**
 * MarcaCubiertaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarcaCubiertaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarcaCubiertaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MarcaCubierta');
    }
}