<?php

/**
 * MensajesinternosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajesinternosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajesinternosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensajesinternos');
    }
}