<?php

/**
 * NovedadesModificadasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovedadesModificadasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovedadesModificadasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NovedadesModificadas');
    }
}