<?php

/**
 * OpcionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpcionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpcionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opciones');
    }
}