<?php

/**
 * OrdenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ordenes');
    }
}