<?php

/**
 * PasswordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PasswordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PasswordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Passwords');
    }
}