<?php

/**
 * PossateliteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PossateliteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PossateliteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Possatelite');
    }
}