<?php

/**
 * ResponsabilidadivaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponsabilidadivaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponsabilidadivaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Responsabilidadiva');
    }
}