<?php

/**
 * RestriccionclienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestriccionclienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestriccionclienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Restriccioncliente');
    }
}