<?php

/**
 * RestclientetipounidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestclientetipounidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestclientetipounidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Restclientetipounidad');
    }
}