<?php

/**
 * TipotnoordenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipotnoordenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipotnoordenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipotnoordenes');
    }
}