<?php

/**
 * TipounidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipounidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipounidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipounidad');
    }
}