<?php

/**
 * TipoejeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoejeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoejeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipoeje');
    }
}