<?php

/**
 * TiposervicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposervicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposervicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tiposervicio');
    }
}