<?php

/**
 * TurnosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TurnosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TurnosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Turnos');
    }
}