<?php

/**
 * UsuariosxestructurasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosxestructurasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosxestructurasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuariosxestructuras');
    }
}