<?php

/**
 * VtosinternosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtosinternosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtosinternosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vtosinternos');
    }
}