<?php

/**
 * VtvporcronogramaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtvporcronogramaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtvporcronogramaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vtvporcronograma');
    }
}